"""add music_download_status

Revision ID: 00894e1ecf3f
Revises: 39e7044a868a
Create Date: 2025-06-26 21:14:48.813678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00894e1ecf3f'
down_revision: Union[str, None] = '39e7044a868a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 添加新列，设置默认值为'PENDING'
    op.add_column('douyin_data', sa.Column('video_download_status', 
                  sa.Enum('PENDING', 'DOWNLOADING', 'COMPLETED', 'FAILED', 'SKIPPED', 
                          name='downloadstatus'), 
                  nullable=False, 
                  server_default='PENDING',  # 添加默认值
                  comment='下载状态'))
    
    op.add_column('douyin_data', sa.Column('music_download_status', 
                  sa.Enum('PENDING', 'DOWNLOADING', 'COMPLETED', 'FAILED', 'SKIPPED', 
                          name='downloadstatus'), 
                  nullable=False, 
                  server_default='PENDING',  # 添加默认值
                  comment='下载状态'))
    
    op.drop_column('douyin_data', 'music_downloaded')
    op.drop_column('douyin_data', 'download_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('douyin_data', sa.Column('download_status', sa.VARCHAR(length=11), nullable=False, server_default='PENDING'))
    op.add_column('douyin_data', sa.Column('music_downloaded', sa.BOOLEAN(), nullable=True))
    op.drop_column('douyin_data', 'music_download_status')
    op.drop_column('douyin_data', 'video_download_status')
    # ### end Alembic commands ###
