"""add image_download_urls

Revision ID: 0c1a62a43d76
Revises: dd77ab62d7a0
Create Date: 2025-06-26 11:02:22.336466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.base import JsonList  # 正确导入 JsonList


# revision identifiers, used by Alembic.
revision: str = '0c1a62a43d76'
down_revision: Union[str, None] = 'dd77ab62d7a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('douyin_data', sa.Column('image_download_urls', JsonList(), nullable=True, comment='图片下载URL列表'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('douyin_data', 'image_download_urls')
    # ### end Alembic commands ###
