"""initial_migration

Revision ID: 2cd3ca7a99f0
Revises: 
Create Date: 2025-06-22 14:34:55.285911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cd3ca7a99f0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('douyin',
    sa.Column('aweme_id', sa.String(length=255), nullable=False),
    sa.Column('video_digg', sa.Integer(), nullable=True, comment='点赞数'),
    sa.Column('video_comment', sa.Integer(), nullable=True, comment='评论数'),
    sa.Column('video_original_url', sa.String(length=255), nullable=True, comment='视频链接'),
    sa.Column('video_duration', sa.String(length=255), nullable=True, comment='视频时长(秒)'),
    sa.Column('video_width', sa.Integer(), nullable=True, comment='视频宽度'),
    sa.Column('video_height', sa.Integer(), nullable=True, comment='视频高度'),
    sa.Column('video_datasize', sa.Integer(), nullable=True, comment='视频文件大小(字节)'),
    sa.Column('video_hashtag_name', sa.Text(), nullable=True, comment='视频标签名称'),
    sa.Column('video_create_time', sa.DateTime(), nullable=True, comment='视频创建时间'),
    sa.Column('video_download_urls', sa.Text(), nullable=True, comment='视频下载URL'),
    sa.Column('author', sa.String(length=255), nullable=True, comment='作者名称'),
    sa.Column('video_title', sa.Text(), nullable=True, comment='视频标题'),
    sa.Column('download_status', sa.Enum('PENDING', 'DOWNLOADING', 'COMPLETED', 'FAILED', 'SKIPPED', name='downloadstatus'), nullable=False, comment='下载状态'),
    sa.Column('download_time', sa.DateTime(), nullable=True, comment='下载时间'),
    sa.Column('download_path', sa.Text(), nullable=True, comment='下载路径'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_douyin_aweme_id'), 'douyin', ['aweme_id'], unique=True)
    op.create_index(op.f('ix_douyin_id'), 'douyin', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_douyin_id'), table_name='douyin')
    op.drop_index(op.f('ix_douyin_aweme_id'), table_name='douyin')
    op.drop_table('douyin')
    # ### end Alembic commands ###
