"""add bool of need to download

Revision ID: 39e7044a868a
Revises: 0c1a62a43d76
Create Date: 2025-06-26 14:54:43.440563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e7044a868a'
down_revision: Union[str, None] = '0c1a62a43d76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('douyin_data', sa.Column('need_download_video', sa.Boolean(), nullable=True, comment='是否需要下载视频'))
    op.add_column('douyin_data', sa.Column('need_download_music', sa.Boolean(), nullable=True, comment='是否需要下载音频'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('douyin_data', 'need_download_music')
    op.drop_column('douyin_data', 'need_download_video')
    # ### end Alembic commands ###
