"""add column vidoe_desc

Revision ID: 3bb5e58059fa
Revises: 9e45cbde6c74
Create Date: 2025-07-02 18:29:08.452936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bb5e58059fa'
down_revision: Union[str, None] = '9e45cbde6c74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('douyin_data', sa.Column('video_desc', sa.Text(), nullable=True, comment='视频描述'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('douyin_data', 'video_desc')
    # ### end Alembic commands ###
