"""add column interactive element

Revision ID: 54d61ed3e99a
Revises: c5e1c625db78
Create Date: 2025-06-24 10:44:08.505798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54d61ed3e99a'
down_revision: Union[str, None] = 'c5e1c625db78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('douyin_data', sa.Column('video_digg_count', sa.Integer(), nullable=True, comment='点赞数'))
    op.add_column('douyin_data', sa.Column('video_comment_count', sa.Integer(), nullable=True, comment='评论数'))
    op.add_column('douyin_data', sa.Column('video_share_count', sa.Integer(), nullable=True, comment='分享数'))
    op.add_column('douyin_data', sa.Column('video_collect_count', sa.Integer(), nullable=True, comment='收藏数'))
    op.drop_column('douyin_data', 'video_digg')
    op.drop_column('douyin_data', 'video_comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('douyin_data', sa.Column('video_comment', sa.INTEGER(), nullable=True))
    op.add_column('douyin_data', sa.Column('video_digg', sa.INTEGER(), nullable=True))
    op.drop_column('douyin_data', 'video_collect_count')
    op.drop_column('douyin_data', 'video_share_count')
    op.drop_column('douyin_data', 'video_comment_count')
    op.drop_column('douyin_data', 'video_digg_count')
    # ### end Alembic commands ###
