"""add_music_fields

Revision ID: 59c09ec7aaa9
Revises: 3aee8a7127d2
Create Date: 2025-06-22 21:22:25.277426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59c09ec7aaa9'
down_revision: Union[str, None] = '3aee8a7127d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('douyin_data', sa.Column('music_download_urls', app.core.utils.JsonList(), nullable=True, comment='音频下载URL列表'))
    op.add_column('douyin_data', sa.Column('music_name', sa.String(length=255), nullable=True, comment='音频名称'))
    op.alter_column('douyin_data', 'video_original_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('douyin_data', 'video_original_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('douyin_data', 'music_name')
    op.drop_column('douyin_data', 'music_download_urls')
    # ### end Alembic commands ###
