"""change width&high to resolution

Revision ID: 611fd89f72ed
Revises: 195887a3f578
Create Date: 2025-06-24 22:46:18.187829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '611fd89f72ed'
down_revision: Union[str, None] = '195887a3f578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('douyin_data', sa.Column('resolution', sa.String(length=255), nullable=True, comment='视频分辨率'))
    op.drop_column('douyin_data', 'video_height')
    op.drop_column('douyin_data', 'video_width')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('douyin_data', sa.Column('video_width', sa.INTEGER(), nullable=True))
    op.add_column('douyin_data', sa.Column('video_height', sa.INTEGER(), nullable=True))
    op.drop_column('douyin_data', 'resolution')
    # ### end Alembic commands ###
