"""add download_time

Revision ID: 7b7629da2a4e
Revises: 611fd89f72ed
Create Date: 2025-06-24 22:47:45.111514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7629da2a4e'
down_revision: Union[str, None] = '611fd89f72ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('douyin_data', sa.Column('download_time', sa.DateTime(), nullable=True, comment='下载时间'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('douyin_data', 'download_time')
    # ### end Alembic commands ###
