"""add column categories

Revision ID: 9e45cbde6c74
Revises: f714b16560c4
Create Date: 2025-06-30 06:32:57.706997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e45cbde6c74'
down_revision: Union[str, None] = 'f714b16560c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 尝试添加列，如果已存在则忽略错误


    try:
        op.add_column('douyin_data',
                      sa.Column('video_categories', sa.String(length=255), nullable=True, comment='视频分类'))
    except Exception as e:
        # 检查是否是"列已存在"错误
        if "duplicate column" in str(e):
            pass  # 忽略错误，列已存在
        else:
            raise  # 其他错误则重新抛出


def downgrade() -> None:
    """Downgrade schema."""

    op.drop_column('douyin_data', 'video_categories')
    # ### end Alembic commands ###
