"""add column media_type

Revision ID: c5e1c625db78
Revises: eb72cd6c9c80
Create Date: 2025-06-24 09:24:29.117605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5e1c625db78'
down_revision: Union[str, None] = 'eb72cd6c9c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('douyin_data', sa.Column('media_type', sa.String(length=255), nullable=True, comment='媒体类型'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('douyin_data', 'media_type')
    # ### end Alembic commands ###
