"""add download_duration field

Revision ID: cde67f15e756
Revises: 5b0047220fd5
Create Date: 2025-06-23 15:21:43.764650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cde67f15e756'
down_revision: Union[str, None] = '5b0047220fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('douyin_data', sa.Column('download_duration', sa.Float(), nullable=True, comment='下载耗时(秒)'))
    op.drop_column('douyin_data', 'download_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('douyin_data', sa.Column('download_time', sa.DATETIME(), nullable=True))
    op.drop_column('douyin_data', 'download_duration')
    # ### end Alembic commands ###
