"""change media_type to aweme_type

Revision ID: dd77ab62d7a0
Revises: 7b7629da2a4e
Create Date: 2025-06-25 15:19:30.310899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd77ab62d7a0'
down_revision: Union[str, None] = '7b7629da2a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('douyin_data', sa.Column('aweme_type', sa.String(length=255), nullable=True, comment='媒体类型'))
    op.drop_column('douyin_data', 'media_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('douyin_data', sa.Column('media_type', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('douyin_data', 'aweme_type')
    # ### end Alembic commands ###
