"""add cloume music

Revision ID: eb72cd6c9c80
Revises: cde67f15e756
Create Date: 2025-06-23 16:42:04.824583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb72cd6c9c80'
down_revision: Union[str, None] = 'cde67f15e756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('douyin_data', sa.Column('music_downloaded', sa.Boolean(), nullable=True, comment='是否已下载音频'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('douyin_data', 'music_downloaded')
    # ### end Alembic commands ###
