"""modify the column  video_resolution

Revision ID: f714b16560c4
Revises: 00894e1ecf3f
Create Date: 2025-06-27 17:30:55.996288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f714b16560c4'
down_revision: Union[str, None] = '00894e1ecf3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 对于SQLite，我们只能添加列和删除列，不能修改列属性
    # 先添加新列（如果不存在）
    try:
        op.add_column('douyin_data', sa.Column('video_resolution', sa.String(length=255), nullable=True, comment='视频分辨率'))
    except Exception:
        # 如果列已存在，忽略错误
        pass
    
    # 删除旧列
    op.drop_column('douyin_data', 'resolution')
    
    # 注意：SQLite不支持ALTER COLUMN修改列属性，所以我们跳过这些操作
    # 如果确实需要修改列属性，需要使用batch操作
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('douyin_data', sa.Column('resolution', sa.VARCHAR(length=255), nullable=True))
    
    # 尝试删除列，如果存在的话
    try:
        op.drop_column('douyin_data', 'video_resolution')
    except Exception:
        # 如果列不存在，忽略错误
        pass
    # ### end Alembic commands ###
