"""The structured selection attachment (agent-layer spec §5.3).

What a writer selects in the script editor and hands to the agent travels as
a HANDLE, not as copied text:

    {"scene_id": "...", "element_ids": ["el_8cde5e3a", ...], "summary_text": "..."}

The spec's table is blunt about why (§5.3): today "原文被复制成纯文本塞进输入
框", and the consequence is that the agent "只能吐新文字,人工粘回" — it can
only emit replacement prose for a human to paste back, because it has no
stable reference to what was selected. ``script_scenes.content_json`` already
gives every element a stable id; using those ids as the payload is what lets
``ProposeEdit`` / ``ApplyEdit`` address the exact passage, and what lets A5's
edit-safety contract decide whether THAT passage moved under the agent (see
``scoped_script_gateway.apply_element_edit``).

``summary_text`` is for HUMANS AND LOGS ONLY — the chip the panel renders
("选自 场景 1 · 2 个元素") and the transcript line. It is never the thing
edited and never trusted as content: the authoritative text always comes from
re-reading ``content_json`` by id. Treating it as content would quietly
reintroduce the copied-blob failure this shape exists to end.

Two entry points, deliberately different in strictness:

  * :class:`ScriptSelectionAttachment` — the HTTP body shape (A7's panel
    posts it). Pydantic validation, hard errors on malformed input.
  * :func:`parse_selection` — the same shape arriving as LLM tool arguments,
    where a malformed value is an everyday occurrence rather than a client
    bug, so it returns a typed rejection instead of raising.

NEITHER of them authorizes anything. ``scene_id`` here is a model- or
client-supplied id and stays a mere SELECTOR until
``script_selection.resolve_selection`` runs it through A2's
``resolve_scene`` — see that module.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Optional

from pydantic import BaseModel, Field, field_validator

# A selection is a passage a human dragged over, not a whole script. THE
# single source for this bound: ``screenwriting_tools`` imports it as
# ``_MAX_ELEMENT_IDS`` rather than keeping A4's own literal, so the HTTP path
# and the tool path cannot drift into refusing at different sizes (one
# silently truncating what the other accepted).
MAX_SELECTION_ELEMENTS = 50

# Bound on the human-facing summary. Long enough for a couple of lines of
# dialogue in the chip, short enough that nobody is tempted to round-trip the
# whole passage through it (see the module docstring on why that matters).
MAX_SUMMARY_CHARS = 500


class ScriptSelectionAttachment(BaseModel):
    """A selection anchored to element ids. The HTTP-body shape."""

    scene_id: str = Field(..., min_length=1)
    element_ids: list[str] = Field(..., min_length=1, max_length=MAX_SELECTION_ELEMENTS)
    summary_text: str = Field(default="", max_length=MAX_SUMMARY_CHARS)

    @field_validator("element_ids")
    @classmethod
    def _clean_element_ids(cls, value: list[str]) -> list[str]:
        """Strip, drop blanks, de-duplicate — preserving selection order.

        Order is preserved because it is the reading order of the passage,
        which is what a human sees in the chip and what the agent should
        reason about; a ``set`` here would scramble it. Duplicates are
        dropped rather than rejected: a selection dragged across a rendered
        element boundary can legitimately report the same id twice, and that
        is a UI artifact, not a client error."""
        seen: set[str] = set()
        out: list[str] = []
        for raw in value:
            eid = str(raw).strip()
            if not eid or eid in seen:
                continue
            seen.add(eid)
            out.append(eid)
        if not out:
            raise ValueError("element_ids must contain at least one non-empty id")
        return out


@dataclass(frozen=True)
class SelectionRejected:
    """A selection payload that never became a selection. ``code`` is what
    the model/panel branches on; ``message`` is what a human reads."""

    code: str
    message: str


@dataclass(frozen=True)
class ParsedSelection:
    """A syntactically valid selection. NOT yet authorized and NOT yet known
    to match any real element — ``resolve_selection`` does both."""

    scene_id: str
    element_ids: tuple[str, ...]
    summary_text: str


def parse_selection(raw: Any) -> Any:
    """Validate a selection arriving as LLM tool arguments.

    Returns :class:`ParsedSelection` or :class:`SelectionRejected` — never
    raises, because these arguments are generated by a model and a malformed
    one must come back as a tool result the model can correct, not as an
    exception in the agent loop (the house convention documented at the top
    of ``screenwriting_tools.py``).
    """
    if not isinstance(raw, dict):
        return SelectionRejected(
            "invalid_selection",
            "selection must be an object with scene_id and element_ids",
        )

    scene_id = str(raw.get("scene_id") or "").strip()
    if not scene_id:
        return SelectionRejected("invalid_selection", "selection.scene_id is required")

    element_ids = raw.get("element_ids")
    if isinstance(element_ids, str):
        # A model that names a single element commonly emits the bare string.
        element_ids = [element_ids]
    if not isinstance(element_ids, list) or not element_ids:
        return SelectionRejected(
            "invalid_selection",
            "selection.element_ids must be a non-empty list of element ids",
        )

    seen: set[str] = set()
    cleaned: list[str] = []
    for item in element_ids[:MAX_SELECTION_ELEMENTS]:
        eid = str(item).strip()
        if not eid or eid in seen:
            continue
        seen.add(eid)
        cleaned.append(eid)
    if not cleaned:
        return SelectionRejected(
            "invalid_selection",
            "selection.element_ids contained no usable element id",
        )

    summary = str(raw.get("summary_text") or "").strip()[:MAX_SUMMARY_CHARS]
    return ParsedSelection(
        scene_id=scene_id, element_ids=tuple(cleaned), summary_text=summary
    )


def selection_from_attachment(
    attachment: Optional[ScriptSelectionAttachment],
) -> Optional[ParsedSelection]:
    """Bridge the HTTP shape to the internal one, so the panel payload and a
    model-supplied selection converge on ONE value object before anything
    downstream (resolution, the edit contract) sees them."""
    if attachment is None:
        return None
    return ParsedSelection(
        scene_id=attachment.scene_id,
        element_ids=tuple(attachment.element_ids),
        summary_text=attachment.summary_text,
    )


__all__ = [
    "MAX_SELECTION_ELEMENTS",
    "MAX_SUMMARY_CHARS",
    "ParsedSelection",
    "ScriptSelectionAttachment",
    "SelectionRejected",
    "parse_selection",
    "selection_from_attachment",
]
