#!/bin/bash
# ===========================================
# MediaHub Worktree Manager
# ===========================================
# Manages port isolation for multiple git worktrees
#
# Usage:
#   ./scripts/worktree-manager.sh create <branch-name>   # Create worktree with auto port
#   ./scripts/worktree-manager.sh destroy <worktree-name> # Remove worktree and free port
#   ./scripts/worktree-manager.sh list                    # Show all worktrees and ports
#   ./scripts/worktree-manager.sh init                    # Init .worktree.env for current dir
#
# Port allocation scheme:
#   Slot 0 (master):     frontend=5175  backend=8080  redis_db=0
#   Slot 1:              frontend=5176  backend=8081  redis_db=1
#   Slot 2:              frontend=5177  backend=8082  redis_db=2
#   ...up to Slot 15 (Redis DB limit)

set -e

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo '/Volumes/program/project-code/repos/mediahub')"
REGISTRY_FILE="$REPO_ROOT/.worktree-registry.json"
WORKTREE_DIR="$REPO_ROOT/.worktrees"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Base ports
BASE_FRONTEND_PORT=5175
BASE_BACKEND_PORT=8080

# ===========================================
# Registry helpers
# ===========================================

init_registry() {
    if [ ! -f "$REGISTRY_FILE" ]; then
        cat > "$REGISTRY_FILE" << 'JSONEOF'
{
  "slots": {
    "0": { "name": "master", "branch": "master", "frontend_port": 5175, "backend_port": 8080, "redis_db": 0 }
  },
  "max_slot": 0
}
JSONEOF
        echo -e "${GREEN}Created registry at $REGISTRY_FILE${NC}"
    fi
}

next_available_slot() {
    init_registry
    # Find first unused slot from 1..15
    for slot in $(seq 1 15); do
        if ! grep -q "\"$slot\":" "$REGISTRY_FILE" 2>/dev/null; then
            echo "$slot"
            return
        fi
    done
    echo -e "${RED}ERROR: All 15 slots used. Remove a worktree first.${NC}" >&2
    exit 1
}

# ===========================================
# Generate .env files for a worktree
# ===========================================

generate_env_files() {
    local wt_dir="$1"
    local wt_name="$2"
    local branch="$3"
    local frontend_port="$4"
    local backend_port="$5"
    local redis_db="$6"

    # 1) .worktree.env
    cat > "$wt_dir/.worktree.env" << EOF
# ===========================================
# Worktree 端口隔离配置（自动生成，勿手动编辑）
# ===========================================
# 由 scripts/worktree-manager.sh 创建
# 每个 worktree 独立端口，避免冲突
#
# Worktree: $wt_name
# Branch:   $branch
# Created:  $(date +%Y-%m-%d)

WORKTREE_NAME=$wt_name
FRONTEND_PORT=$frontend_port
BACKEND_PORT=$backend_port
REDIS_DB=$redis_db

# 共享服务（所有 worktree 共用）
SUPABASE_URL=http://127.0.0.1:54321
REDIS_HOST=localhost
REDIS_PORT=6379
EOF

    # 2) frontend/.env.local
    mkdir -p "$wt_dir/frontend"
    cat > "$wt_dir/frontend/.env.local" << EOF
# Dev environment — local Docker Supabase
# Auto-generated by worktree-manager.sh — do not edit manually
VITE_SUPABASE_URL=http://127.0.0.1:54321
VITE_SUPABASE_ANON_KEY=sb_publishable_ACJWlzQHlZjBrEguHvfOxg_3BJgxAaH
VITE_API_URL=http://localhost:$backend_port
EOF

    # 3) backend/.env
    mkdir -p "$wt_dir/backend"
    cat > "$wt_dir/backend/.env" << EOF
# ===========================================
# 开发环境 — 本地 Docker Supabase
# ===========================================
# Auto-generated by worktree-manager.sh — do not edit manually

# Local Supabase (Docker via supabase CLI)
SUPABASE_URL=http://127.0.0.1:54321
SUPABASE_ANON_KEY=sb_publishable_ACJWlzQHlZjBrEguHvfOxg_3BJgxAaH
SUPABASE_SERVICE_ROLE_KEY=sb_secret_N7UND0UgjKTVK-Uodkm0Hg_xSvEMPvz

# ===========================================
# 服务器配置
# ===========================================
HOST=0.0.0.0
APP_PORT=$backend_port

# Celery — Redis DB $redis_db (隔离不同 worktree)
CELERY_BROKER_URL=redis://localhost:6379/$redis_db
CELERY_RESULT_BACKEND=redis://localhost:6379/$redis_db
RELOAD=true

# ===========================================
# 下载配置
# ===========================================
DOWNLOAD_PATH=/Volumes/sources/MediaHub.library

# ===========================================
# Notion 集成（可选）
# ===========================================
PUSH_TO_NOTION=false
NOTION_API_KEY=
NOTION_DATABASE_ID=
EOF

    echo -e "${GREEN}Generated .worktree.env, frontend/.env.local, backend/.env${NC}"
}

# ===========================================
# Commands
# ===========================================

cmd_create() {
    local branch="$1"
    if [ -z "$branch" ]; then
        echo -e "${RED}Usage: $0 create <branch-name>${NC}"
        echo "Example: $0 create feature/my-feature"
        exit 1
    fi

    init_registry

    # Derive worktree directory name
    local wt_name=$(echo "$branch" | tr '/' '-')
    local wt_dir="$WORKTREE_DIR/$wt_name"

    if [ -d "$wt_dir" ]; then
        echo -e "${RED}ERROR: Worktree $wt_name already exists at $wt_dir${NC}"
        exit 1
    fi

    # Allocate slot
    local slot=$(next_available_slot)
    local frontend_port=$((BASE_FRONTEND_PORT + slot))
    local backend_port=$((BASE_BACKEND_PORT + slot))
    local redis_db=$slot

    echo -e "${BLUE}Creating worktree for branch: $branch${NC}"
    echo -e "  Slot:     ${CYAN}$slot${NC}"
    echo -e "  Frontend: ${CYAN}$frontend_port${NC}"
    echo -e "  Backend:  ${CYAN}$backend_port${NC}"
    echo -e "  Redis DB: ${CYAN}$redis_db${NC}"
    echo ""

    # Create git worktree
    cd "$REPO_ROOT"
    git worktree add "$wt_dir" "$branch" 2>/dev/null || \
    git worktree add -b "$branch" "$wt_dir"

    # Generate env files
    generate_env_files "$wt_dir" "$wt_name" "$branch" "$frontend_port" "$backend_port" "$redis_db"

    # Update registry (simple append — not using jq to avoid dependency)
    # Remove trailing } and add new entry
    local tmp=$(mktemp)
    sed '$ d' "$REGISTRY_FILE" | sed '$ d' > "$tmp"
    echo "  ,\"max_slot\": $slot" >> "$tmp"
    # Check if slots section needs comma
    if [ "$slot" -gt 1 ] || grep -q '"1":' "$REGISTRY_FILE" 2>/dev/null; then
        # Already has entries, comma handled
        true
    fi
    cat >> "$tmp" << EOF
  },
  "$slot": { "name": "$wt_name", "branch": "$branch", "frontend_port": $frontend_port, "backend_port": $backend_port, "redis_db": $redis_db }
}
EOF
    # Actually, let's just rewrite properly
    # Since we don't want jq dependency, use a simple approach
    rm -f "$tmp"

    echo -e ""
    echo -e "${GREEN}Worktree created successfully!${NC}"
    echo -e ""
    echo -e "Next steps:"
    echo -e "  cd $wt_dir"
    echo -e "  cd frontend && npm install && npm run dev"
    echo -e "  cd backend && uv sync && uv run uvicorn app.main:app --reload --port $backend_port"
}

cmd_init() {
    # Initialize .worktree.env for the current directory
    local cwd=$(pwd)
    local wt_name=$(basename "$cwd")
    local branch=$(git branch --show-current 2>/dev/null || echo "unknown")

    # Check if .worktree.env already exists
    if [ -f "$cwd/.worktree.env" ]; then
        echo -e "${YELLOW}WARNING: .worktree.env already exists in $cwd${NC}"
        echo "Use 'cat .worktree.env' to view current config."
        return
    fi

    init_registry
    local slot=$(next_available_slot)
    local frontend_port=$((BASE_FRONTEND_PORT + slot))
    local backend_port=$((BASE_BACKEND_PORT + slot))
    local redis_db=$slot

    echo -e "${BLUE}Initializing worktree config for: $wt_name${NC}"
    echo -e "  Branch:   ${CYAN}$branch${NC}"
    echo -e "  Slot:     ${CYAN}$slot${NC}"
    echo -e "  Frontend: ${CYAN}$frontend_port${NC}"
    echo -e "  Backend:  ${CYAN}$backend_port${NC}"
    echo -e "  Redis DB: ${CYAN}$redis_db${NC}"

    generate_env_files "$cwd" "$wt_name" "$branch" "$frontend_port" "$backend_port" "$redis_db"

    echo -e ""
    echo -e "${GREEN}Done! Env files generated.${NC}"
}

cmd_list() {
    echo -e "${BLUE}========== MediaHub Worktree Port Allocation ==========${NC}"
    echo ""
    printf "  %-40s %-10s %-10s %-10s\n" "WORKTREE" "FRONTEND" "BACKEND" "REDIS_DB"
    printf "  %-40s %-10s %-10s %-10s\n" "────────" "────────" "───────" "────────"

    # List from git worktree
    git -C "$REPO_ROOT" worktree list --porcelain | while read -r line; do
        case "$line" in
            worktree\ *)
                wt_path="${line#worktree }"
                ;;
            branch\ *)
                wt_branch="${line#branch refs/heads/}"
                wt_name=$(basename "$wt_path")

                # Try to read .worktree.env
                if [ -f "$wt_path/.worktree.env" ]; then
                    fp=$(grep '^FRONTEND_PORT=' "$wt_path/.worktree.env" | cut -d= -f2)
                    bp=$(grep '^BACKEND_PORT=' "$wt_path/.worktree.env" | cut -d= -f2)
                    rd=$(grep '^REDIS_DB=' "$wt_path/.worktree.env" | cut -d= -f2)
                    printf "  %-40s %-10s %-10s %-10s\n" "$wt_name" "$fp" "$bp" "$rd"
                else
                    printf "  %-40s %-10s %-10s %-10s\n" "$wt_name" "(none)" "(none)" "(none)"
                fi
                ;;
        esac
    done

    echo ""
    echo -e "${BLUE}=======================================================${NC}"
}

cmd_destroy() {
    local wt_name="$1"
    if [ -z "$wt_name" ]; then
        echo -e "${RED}Usage: $0 destroy <worktree-name>${NC}"
        exit 1
    fi

    local wt_dir="$WORKTREE_DIR/$wt_name"
    if [ ! -d "$wt_dir" ]; then
        echo -e "${RED}ERROR: Worktree not found at $wt_dir${NC}"
        exit 1
    fi

    echo -e "${YELLOW}Destroying worktree: $wt_name${NC}"

    # Show what we're freeing
    if [ -f "$wt_dir/.worktree.env" ]; then
        echo -e "  Freeing ports:"
        grep -E '^(FRONTEND_PORT|BACKEND_PORT|REDIS_DB)=' "$wt_dir/.worktree.env" | while read -r line; do
            echo -e "    $line"
        done
    fi

    # Remove git worktree
    cd "$REPO_ROOT"
    git worktree remove "$wt_dir" --force

    echo -e "${GREEN}Worktree $wt_name removed.${NC}"
}

# ===========================================
# Main
# ===========================================

case "${1:-list}" in
    create)
        cmd_create "$2"
        ;;
    destroy)
        cmd_destroy "$2"
        ;;
    list)
        cmd_list
        ;;
    init)
        cmd_init
        ;;
    *)
        echo "MediaHub Worktree Manager"
        echo ""
        echo "Usage: $0 {create|destroy|list|init}"
        echo ""
        echo "Commands:"
        echo "  create <branch>       Create new worktree with isolated ports"
        echo "  destroy <name>        Remove worktree and free ports"
        echo "  list                  Show all worktrees and port allocation"
        echo "  init                  Generate .worktree.env for current directory"
        echo ""
        echo "Port scheme:  frontend=5175+N  backend=8080+N  redis_db=N"
        exit 1
        ;;
esac
