-- supabase/migrations/229_auto_create_personal_team.sql
-- Recon result (Case X): handle_new_user() already creates a team on auth.users
-- INSERT (mig 053), but after mig 227 added kind='collaborative' as the column
-- DEFAULT, the auto-created team lands as kind='collaborative' instead of
-- kind='personal'.  This migration redefines handle_new_user() to explicitly
-- set kind='personal' on the auto-created workspace team so new users always
-- start with exactly one personal team.
--
-- Notes:
--   • invite_code is auto-generated by the teams_invite_code_trigger (mig 009)
--     when invite_code IS NULL, so we omit it from the INSERT.
--   • teams_add_owner_trigger (add_owner_as_member, mig 009) fires on teams
--     INSERT and inserts the owner into team_members automatically — no
--     separate team_members INSERT needed here.
--   • The function is SECURITY DEFINER SET search_path = public so it can
--     write to public.teams + public.user_profiles from the auth schema context.
--   • Idempotent via ON CONFLICT(id) DO NOTHING on user_profiles and via
--     the uq_teams_owner_personal unique partial index on teams (mig 227)
--     which prevents a second personal team for the same owner.
-- See docs/superpowers/specs/2026-05-28-id-unification-design.md § 3.

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
    uname TEXT;
BEGIN
    uname := COALESCE(
        NEW.raw_user_meta_data->>'username',
        split_part(NEW.email, '@', 1)
    );

    -- Create user profile (idempotent)
    INSERT INTO public.user_profiles (id, username, role)
    VALUES (NEW.id, uname, 'user')
    ON CONFLICT (id) DO NOTHING;

    -- Auto-create personal team.
    -- kind='personal' is explicit so the column DEFAULT ('collaborative')
    -- does not take effect.
    -- Idempotent: uq_teams_owner_personal prevents a second personal team.
    INSERT INTO public.teams (name, owner_id, kind)
    VALUES (
        uname || '''s Workspace',
        NEW.id,
        'personal'
    )
    ON CONFLICT DO NOTHING;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;
